
package Frontend;


import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class LoginPanel extends javax.swing.JPanel {

    
    private final  String admin = "admin";
    private final String password = "1234";
   private boolean correctuser = false , correctpassword = false;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        
        btnDisabled();
        validationstart();
    }
    
private void btnDisabled(){
submitbtn.setEnabled(false);
submitbtn.setBackground(new java.awt.Color(105, 105, 105));
submitbtn.setForeground(Color.black);



}
private void btnEnable(){

submitbtn.setEnabled(true);
submitbtn.setBackground(new java.awt.Color(82, 235, 82));
submitbtn.setForeground(Color.black);

}




private void validationstart(){
    
    usernameError.setVisible(false);
    passwordError.setVisible(false);
    usernameField.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            ((CustomdesignClasses.roundedins)usernameField).setBorderColor(Color.ORANGE);
             
             checkuser();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            ((CustomdesignClasses.roundedins)usernameField).setBorderColor(Color.ORANGE);
             
            checkuser();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
        
        private void checkuser(){
        String error = validateIN_user(usernameField.getText().trim());
        if(!error.isEmpty()){
            ((CustomdesignClasses.roundedins)usernameField).setBorderColor(Color.RED);
             
            usernameError.setText(error);
        usernameError.setVisible(true);
        
        
        }
        else{
            ((CustomdesignClasses.roundedins)usernameField).setBorderColor(Color.RED);
             
            
            usernameError.setText(error);
        usernameError.setVisible(false);
        
        }
        if(correctuser){
            ((CustomdesignClasses.roundedins)usernameField).setBorderColor(Color.GREEN);
             
        
        }
        if(correctpassword && correctuser){
            btnEnable();
        }
        else{
        btnDisabled();
        }
        }
    });
    passwordField.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            ((CustomdesignClasses.roundedPASS)passwordField).setBorderColor(Color.orange);
             checkuser();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            ((CustomdesignClasses.roundedPASS)passwordField).setBorderColor(Color.ORANGE);
            checkuser();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
        
        private void checkuser(){
        String error = validateIN_Pass(passwordField.getText().trim());
        if(!error.isEmpty()){
            ((CustomdesignClasses.roundedPASS)passwordField).setBorderColor(Color.RED);
        passwordError.setText(error);
        passwordError.setVisible(true);
        
        }
        else{
            ((CustomdesignClasses.roundedPASS)passwordField).setBorderColor(Color.RED);
            passwordError.setText(error);
        passwordError.setVisible(false);
        
        }
        if(correctpassword){
        ((CustomdesignClasses.roundedPASS)passwordField).setBorderColor(Color.green);
        }
         if(correctpassword && correctuser){
            btnEnable();
        }
        else{
        btnDisabled();
        }
        }
    });
}
private final String validateIN_Pass(String s){

correctpassword = false;
if(s.isEmpty()){
return "   PASSWORD CANNOT BE EMPTY";

}
else if(!s.equals(password)){
return "   PASSWORD NOT VALID";

}
correctpassword = true;
return "";

}

private final String validateIN_user(String s){
correctuser = false;
if(s.isEmpty()){
return "   USERNAME CANNOT BE EMPTY";

}
else if(!s.equals(admin)){
return "   USERNAME NOT VALID";

}
correctuser = true;
return "";

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    private void initComponents() {


    Title = new javax.swing.JLabel();
    inputs_errors = new javax.swing.JPanel();
    usernameLabel = new javax.swing.JLabel();
    passwordLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JPasswordField();
    usernameField = new javax.swing.JTextField();
    usernameError = new javax.swing.JLabel();
    passwordError = new javax.swing.JLabel();
    submitbtn = new javax.swing.JButton();

    Title.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
    Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Title.setText("LOGIN");
    Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    usernameLabel.setLabelFor(usernameField);
    usernameLabel.setText("USERNAME");

    passwordLabel.setLabelFor(passwordField);
    passwordLabel.setText("PASSWORD");
usernameField  = new CustomdesignClasses.roundedins(5, 5);
    usernameField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            usernameFieldActionPerformed(evt);
        }
    });

usernameError  = new CustomdesignClasses.roundedlabel("", 5, 5);
    usernameError.setBackground(new java.awt.Color(255, 0, 51));
    usernameError.setForeground(new java.awt.Color(0, 0, 0));
usernameError.setPreferredSize(new java.awt.Dimension(0, 22)); 
usernameError.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 22)); 




passwordField  =  new CustomdesignClasses.roundedPASS(5,5);
passwordError  = new CustomdesignClasses.roundedlabel("", 5, 5);
    passwordError.setBackground(new java.awt.Color(204, 0, 102));
    passwordError.setForeground(new java.awt.Color(0, 0, 0));
passwordError.setPreferredSize(new java.awt.Dimension(passwordError.getPreferredSize().width, 20));
passwordError.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 20));



    submitbtn = new CustomdesignClasses.roundedbtn("SUBMIT", 20, 20);
    submitbtn.setBackground(Color.GRAY);
    submitbtn.setForeground(Color.BLACK);
    submitbtn.setEnabled(false);
    
    submitbtn.addActionListener(l ->{
    if(correctpassword && correctuser){
       javax.swing.JOptionPane.showMessageDialog(this, "SUCCESSFUL LOGIN");
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        window.dispose();
        new MainFrame().setVisible(true);
        
    }
    else{
     javax.swing.JOptionPane.showMessageDialog(this, "iNVALID USERNAME OR PASSWORD");
    }
        
        
    
    });
    

    javax.swing.GroupLayout inputs_errorsLayout = new javax.swing.GroupLayout(inputs_errors);
    inputs_errors.setLayout(inputs_errorsLayout);
    inputs_errorsLayout.setHorizontalGroup(
        inputs_errorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(inputs_errorsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(inputs_errorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inputs_errorsLayout.createSequentialGroup()
                    .addComponent(usernameLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(usernameField))
                .addGroup(inputs_errorsLayout.createSequentialGroup()
                    .addComponent(passwordLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(inputs_errorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(inputs_errorsLayout.createSequentialGroup()
                            .addComponent(submitbtn)
                            .addGap(0, 130, Short.MAX_VALUE))
                        .addComponent(usernameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passwordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passwordField))))
            .addGap(38, 38, 38))
    );
    inputs_errorsLayout.setVerticalGroup(
        inputs_errorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(inputs_errorsLayout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(inputs_errorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(usernameLabel)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(usernameError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(inputs_errorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(passwordLabel)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(passwordError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(submitbtn))
    );

    javax.swing.JPanel formPanel = new javax.swing.JPanel();
    formPanel.setLayout(new javax.swing.BoxLayout(formPanel, javax.swing.BoxLayout.Y_AXIS));
    formPanel.add(Title);
    Title.setAlignmentX(CENTER_ALIGNMENT);
inputs_errors.setAlignmentX(CENTER_ALIGNMENT);
    formPanel.add(inputs_errors);
    formPanel.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(Color.BLACK, 2, true),
        BorderFactory.createEmptyBorder(15, 15, 15, 15)
    ));

   javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
   this.setLayout(layout);

   layout.setHorizontalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
           .addGroup(layout.createSequentialGroup()
           .addGap(0, 0, Short.MAX_VALUE)
           .addComponent(formPanel)
           .addGap(0, 0, Short.MAX_VALUE))
   );

   layout.setVerticalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
           .addGroup(layout.createSequentialGroup()
           .addGap(0, 0, Short.MAX_VALUE)
           .addComponent(formPanel)
           .addGap(0, 0, Short.MAX_VALUE))
   );

}           
       
 private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed


   
   
    private javax.swing.JLabel Title;
    private javax.swing.JPanel inputs_errors;
    private javax.swing.JLabel passwordError;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel usernameError;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;

  
   
}
